# Generated by Django 5.1.6 on 2025-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailVistaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('customer', models.CharField(max_length=255)),
                ('transport_type', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=50)),
                ('canceled_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
