# Generated by Django 5.1.6 on 2025-03-03 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_rv_canceled_order_rv_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailVistaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('transport_type', models.CharField(max_length=255)),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('canceled_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='rv_canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rv_customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rv_last_synced',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rv_order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rv_reference_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rv_shipping_method',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
