# Generated by Django 5.1.6 on 2025-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_height_remove_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_offers',
            field=models.BooleanField(default=False),
        ),
    ]
